### teste de buscar aluno por ID
POST http://localhost:40000/Login HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MzM5NTk2NSwiZXhwIjoxNjkzMzk2NTY1fQ.LyMUM9sPVB-3nbptws4vCh6-OqYqi1ke2ek9UVwNrOU

{    
    "username": "qwe",
    "password": "qwe"
}


### teste de buscar todos os alunos
GET http://localhost:40000/getAllAlunos HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MzM5NjA1MSwiZXhwIjoxNjkzMzk2NjUxfQ.t3bUXB43XIR65Q6uj8omXrqSPRlaPU8MXL4ZEX1Tno8

{    
    
}

### teste de buscar aluno por ID
POST http://localhost:40000/getAlunoByID HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MzM5NjA1MSwiZXhwIjoxNjkzMzk2NjUxfQ.t3bUXB43XIR65Q6uj8omXrqSPRlaPU8MXL4ZEX1Tno8

{    
    "alunoid": 3
}

### inserção de aluno
POST http://localhost:40000/insertAlunos HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MzM5NjA1MSwiZXhwIjoxNjkzMzk2NjUxfQ.t3bUXB43XIR65Q6uj8omXrqSPRlaPU8MXL4ZEX1Tno8

{    
    "alunoid": 0,
    "prontuario": "pront52",
    "nome": "Carlos das Matias",
    "endereco": " Rua das couves2",
    "rendafamiliar": 10000,
    "datanascimento": "1999-12-12",
    "cursoid": 2,
    "deleted": false
}

### atualização de aluno
POST http://localhost:40000/updateAlunos HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MzM5NjA1MSwiZXhwIjoxNjkzMzk2NjUxfQ.t3bUXB43XIR65Q6uj8omXrqSPRlaPU8MXL4ZEX1Tno8

{    
    "alunoid": 11,
    "prontuario": "pront109",
    "nome": "xJosé das Neves",
    "endereco": "x Rua das couves",
    "rendafamiliar": 0,
    "datanascimento": "1999-12-12",
    "cursoid": 2,
    "deleted": false
}

### teste de atualização de aluno
POST http://localhost:40000/DeleteAlunos HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MzM5NjA1MSwiZXhwIjoxNjkzMzk2NjUxfQ.t3bUXB43XIR65Q6uj8omXrqSPRlaPU8MXL4ZEX1Tno8

{    
    "alunoid": 3
}